name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            swift: "5.8"
          - os: ubuntu-latest
            swift: "5.8"
    steps:
      - name: Setup swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: ${{ matrix.swift }}

      - run: swift --version
      - uses: actions/checkout@v3

      - name: test
        run: swift test

      - name: build for release
        run: swift build -c release
